# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C569-BC8A";
      fsType = "vfat";
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/1bb26d34-c1b6-4d70-aee0-a9ef3a5199ff";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/etc" =
    { device = "/dev/disk/by-uuid/1bb26d34-c1b6-4d70-aee0-a9ef3a5199ff";
      fsType = "btrfs";
      options = [ "subvol=etc" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/1bb26d34-c1b6-4d70-aee0-a9ef3a5199ff";
      fsType = "btrfs";
      options = [ "subvol=log" ];
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/1bb26d34-c1b6-4d70-aee0-a9ef3a5199ff";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/1bb26d34-c1b6-4d70-aee0-a9ef3a5199ff";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/25088bd7-5ead-45b4-b585-fb46ba28b8fa"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp100s0f4u1u1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
